// Mock product data
export const products = [
  {
    id: 1,
    name: "Premium Headphones",
    price: 199.99,
    image: "/placeholder.svg?height=200&width=200",
    description:
      "High-quality wireless headphones with noise cancellation. Features include 30-hour battery life, premium sound quality, and comfortable over-ear design. Perfect for music lovers and professionals alike.",
    features: ["Noise cancellation", "30-hour battery", "Bluetooth 5.0", "Built-in microphone"],
    rating: 4.5,
    reviewCount: 128,
    category: "electronics",
    colors: ["Black", "White", "Blue"],
    sizes: [],
    specifications: [
      { name: "Battery Life", value: "30 hours" },
      { name: "Connectivity", value: "Bluetooth 5.0" },
      { name: "Noise Cancellation", value: "Active" },
      { name: "Weight", value: "250g" },
      { name: "Warranty", value: "2 years" },
    ],
    gallery: [
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
    ],
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 249.99,
    image: "/placeholder.svg?height=200&width=200",
    description:
      "Feature-rich smartwatch with health monitoring. Track your fitness goals, receive notifications, and more with this sleek and stylish smartwatch.",
    features: ["Heart rate monitor", "Sleep tracking", "Water resistant", "7-day battery life"],
    rating: 4.7,
    reviewCount: 95,
    category: "electronics",
    colors: ["Black", "Silver", "Rose Gold"],
    sizes: [],
    specifications: [
      { name: "Battery Life", value: "7 days" },
      { name: "Water Resistance", value: "50m" },
      { name: "Display", value: "AMOLED 1.4 inch" },
      { name: "Sensors", value: "Heart rate, Accelerometer, Gyroscope" },
      { name: "Warranty", value: "1 year" },
    ],
    gallery: [
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
    ],
  },
  {
    id: 3,
    name: "Wireless Earbuds",
    price: 129.99,
    image: "/placeholder.svg?height=200&width=200",
    description:
      "Compact wireless earbuds with premium sound quality. Enjoy your music on the go with these comfortable and stylish earbuds.",
    features: ["Active noise cancellation", "Touch controls", "20-hour battery with case", "Water resistant"],
    rating: 4.2,
    reviewCount: 78,
    category: "electronics",
    colors: ["Black", "White"],
    sizes: [],
    specifications: [
      { name: "Battery Life", value: "5 hours (20 with case)" },
      { name: "Water Resistance", value: "IPX4" },
      { name: "Connectivity", value: "Bluetooth 5.2" },
      { name: "Noise Cancellation", value: "Active" },
      { name: "Warranty", value: "1 year" },
    ],
    gallery: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
  },
  {
    id: 4,
    name: "Bluetooth Speaker",
    price: 89.99,
    image: "/placeholder.svg?height=200&width=200",
    description:
      "Portable speaker with 360° sound and 20-hour battery life. Perfect for outdoor adventures or home use.",
    features: ["360° sound", "20-hour battery", "Water resistant", "Built-in microphone for calls"],
    rating: 4.3,
    reviewCount: 65,
    category: "electronics",
    colors: ["Black", "Blue", "Red"],
    sizes: [],
    specifications: [
      { name: "Battery Life", value: "20 hours" },
      { name: "Water Resistance", value: "IPX7" },
      { name: "Connectivity", value: "Bluetooth 5.0" },
      { name: "Power Output", value: "20W" },
      { name: "Warranty", value: "1 year" },
    ],
    gallery: [
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
    ],
  },
  {
    id: 5,
    name: "Cotton T-Shirt",
    price: 24.99,
    image: "/placeholder.svg?height=200&width=200",
    description: "Premium cotton t-shirt with a comfortable fit. Perfect for everyday wear.",
    features: ["100% cotton", "Machine washable", "Comfortable fit", "Durable fabric"],
    rating: 4.6,
    reviewCount: 210,
    category: "clothing",
    colors: ["Black", "White", "Gray", "Navy", "Red"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    specifications: [
      { name: "Material", value: "100% Cotton" },
      { name: "Care", value: "Machine wash cold" },
      { name: "Fit", value: "Regular" },
      { name: "Country of Origin", value: "USA" },
    ],
    gallery: [
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
    ],
  },
  {
    id: 6,
    name: "Slim Fit Jeans",
    price: 59.99,
    image: "/placeholder.svg?height=200&width=200",
    description: "Stylish slim fit jeans made from high-quality denim. Comfortable and durable for everyday wear.",
    features: ["Slim fit", "High-quality denim", "Stretch fabric", "Multiple pockets"],
    rating: 4.4,
    reviewCount: 175,
    category: "clothing",
    colors: ["Blue", "Black", "Gray"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    specifications: [
      { name: "Material", value: "98% Cotton, 2% Elastane" },
      { name: "Care", value: "Machine wash cold" },
      { name: "Fit", value: "Slim" },
      { name: "Rise", value: "Mid-rise" },
    ],
    gallery: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
  },
  {
    id: 7,
    name: "Coffee Maker",
    price: 79.99,
    image: "/placeholder.svg?height=200&width=200",
    description: "Programmable coffee maker with 12-cup capacity. Perfect for home or office use.",
    features: ["12-cup capacity", "Programmable timer", "Auto shut-off", "Brew strength control"],
    rating: 4.1,
    reviewCount: 120,
    category: "home-kitchen",
    colors: ["Black", "Silver"],
    sizes: [],
    specifications: [
      { name: "Capacity", value: "12 cups" },
      { name: "Timer", value: "24-hour programmable" },
      { name: "Power", value: "1000W" },
      { name: "Warranty", value: "1 year" },
    ],
    gallery: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
  },
  {
    id: 8,
    name: "Stainless Steel Cookware Set",
    price: 149.99,
    image: "/placeholder.svg?height=200&width=200",
    description: "10-piece stainless steel cookware set. Includes pots, pans, and lids for all your cooking needs.",
    features: ["Stainless steel construction", "Dishwasher safe", "Oven safe up to 500°F", "Stay-cool handles"],
    rating: 4.8,
    reviewCount: 85,
    category: "home-kitchen",
    colors: ["Silver"],
    sizes: [],
    specifications: [
      { name: "Material", value: "18/10 Stainless Steel" },
      { name: "Pieces", value: "10" },
      { name: "Dishwasher Safe", value: "Yes" },
      { name: "Induction Compatible", value: "Yes" },
    ],
    gallery: [
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
      "/placeholder.svg?height=200&width=200",
    ],
  },
]

